app:
  name: "web_app"
  mode: "dev"
  port: 8888
  start_time: "2020-02-02"
  mechine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "12345678"
  dbname: "bluebell"
  max_open_conns: 1
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
